openapi: 3.0.2
info:
  title: Games-API
  version: 1.0.0
  description: "### This is a Swagger UI for our Games API\n\n### Error handling\nErrors are presented using the HTTP status codes 400-599. The response include a more detailed explanation about the error in the body.\n\n```\n{\n  \"error\": \"Cleartext explanation of the error that occurred\"\n}\n```\n\n### Generic API errors\nThese error responses can be returned by any of the described endpoints.\n\n| HTTP status  |  Description |\n|---|---|\n| 400| Bad input parameters or invalid request. More information can be found in the response body.\n| 401| The consumer does not have access to the requested resource or the provided token is not valid.\n| 404| The requested resource can not be found or the user does not have access to the resource.\n| 5XX| A server error has occurred while processing the request."
paths:
  /games:
    get:
      tags:
      - games
      summary: Get a list of all games
      description: Returns a list of all games in API
      responses:
        '200':
          description: Returns a list of games
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
              examples:
                List of games:
                  value:
                  - Witcher 3
                  - Cyberpunk 2077
                  - Minecraft
    post:
      tags:
      - new-game
      summary: Creates a game
      description: Creates a new game
      requestBody:
        description: A new game to be created
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/new-game'
      responses:
        '201':
          description: Game was created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/new-game'
              examples:
                Created game:
                  value:
                    id: 9
                    price: 0.99
                    name: Tetris
        '400':
          description: One or all params are missing
          content:
            application/json:
              schema: &id001
                $ref: '#/components/schemas/error'
              examples:
                Params missing:
                  value:
                    error: One or all params are missing
  /games/{id}:
    get:
      tags:
      - details
      summary: Get full details of a game
      description: Returns full details of a given id game
      operationId: id
      responses:
        '200':
          description: Returns full details of a given id game
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
              examples:
                Full details of a given game:
                  value:
                    id: 1
                    name: Witcher 3
                    price: 29.99
        '404':
          description: Game was not found in games array
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
              examples:
                Game /w+ was not found:
                  value:
                    error: Game \w+ was not found in game array
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: integer
    delete:
      tags:
      - delete-game
      summary: Deletes a game
      description: Deletes a game with a given id
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/delete-game'
      responses:
        '204':
          description: Game was deleted successfully
        '404':
          description: Game was not found in games array
          content:
            application/json:
              schema: *id001
              examples:
                Game not found:
                  value:
                    error: Game not found
components:
  schemas:
    error:
      title: Root Type for error
      type: object
      properties:
        error:
          type: string
      example:
        error: Error message.
    new-game:
      title: Root Type for new-game
      type: object
      required:
      - name
      - price
      properties:
        name:
          type: string
        price:
          format: float
          type: number
      example:
        name: Tetris
        price: 0.99
    delete-game:
      title: Root Type for delete-game
      type: object
      required:
      - id
      properties:
        id:
          type: integer
      example:
        id: 1
